-- 1. Tasks Table
create table tasks (
  task_id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  category text,
  is_default boolean default false,
  creator_user uuid references auth.users
);

-- 2. CBT Records Table
create table cbt_record (
  record_id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  task_id bigint references tasks(task_id),
  scheduled_time timestamp with time zone,
  status text check (status in ('pending', 'completed')) default 'pending',
  notify text[] default '{}',
  
  -- CBT Fields
  anxiety_before int,
  anxiety_after int,
  thought_before text,
  feeling_after text,
  belief_adjustment text,
  distortions text[] default '{}'
);

-- Policies
alter table tasks enable row level security;
alter table cbt_record enable row level security;

create policy "Default tasks are viewable by everyone" 
on tasks for select using (is_default = true);

create policy "Users can see own tasks" 
on tasks for select using (auth.uid() = creator_user);

create policy "Users can create tasks" 
on tasks for insert with check (auth.uid() = creator_user);

create policy "Users can delete own tasks" 
on tasks for delete using (auth.uid() = creator_user);

create policy "Users can see own records" 
on cbt_record for select using (auth.uid() = user_id);

create policy "Users can insert own records" 
on cbt_record for insert with check (auth.uid() = user_id);

create policy "Users can update own records" 
on cbt_record for update using (auth.uid() = user_id);

-- Insert Default Tasks (Seed)
insert into tasks (title, category, is_default) values
('深呼吸練習', '放鬆', true),
('正念冥想 10 分鐘', '正念', true),
('寫下三件感恩的事', '感恩', true),
('散步 15 分鐘', '運動', true),
('整理桌面', '環境', true),
('閱讀一章書', '學習', true),
('打電話給朋友', '社交', true);
